pipeline {
    agent any
    tools{
      maven 'maven 3.6.1'
}
    stages{
        stage(one){
          when{
              changeset "java/cmad-ms-users/**"
}
          steps{
            echo 'Compiling users app..'
            dir('users'){
              sh 'mvn compile'
            }
} }
        stage(two){
          when{
            changeset "java/cmad-ms-users/**"
          }
          steps{
            echo 'Running Unit Tets on users app..'
            dir('users'){
                               sh 'mvn clean test'
             }
} }
        stage(three){
          when{
            branch 'master'
            changeset "java/cmad-ms-users/**"
          }
          steps{
            echo 'Packaging users app'
            dir('users'){
              sh 'mvn package -DskipTests'
              archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
} }
}
    post{
      always{
          echo 'Building multibranch pipeline for users is completed..'
      }
} }
